import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import PropertyCard from "../components/PropertyCard";
import ExploreCard from "../components/ExploreCard";
import ApartmentCard from "../components/ApartmentCard";
import Book from "../components/Book";
import Contact from "../components/Contact";
import AMap from "../components/AMap";
const exploreData = [
	{
		location: "Ala Moana Beach Park",
		tag: "beach",
		desc: "A public 100-acre park with a wide gold-sand beach that is over a half-mile long.",
		distance: "3 min walk",
		map: "",
	},
	{
		location: "Waikiki Beach",
		tag: "beach",
		desc: "Oahu's most famous beach ",
		distance: "15 min walk",
		map: "",
	},
	{
		location: "Diamond Head",
		tag: "hike",
		desc: "A volcanic tuff cone on the Hawaiian island of Oʻahu and known to Hawaiians as Lēʻahi. The Hawaiian name is most likely derived from lae plus ʻahi because the shape of the ridgeline resembles the shape of a tuna's dorsal fin.",
		distance: "9 min drive",
		map: "",
	},
	{
		location: "Kaka'ako",
		tag: "shop",
		desc: "Wholefoods, food, farmer's market",
		distance: "12 min drive",
		map: "",
	},

	{
		location: "Ala Moana Mall",
		tag: "shop",
		desc: "A large open-air shopping mall in the Ala Moana neighborhood of Honolulu, Hawaii. Ala Moana is the eleventh largest shopping mall in the United States and the largest open-air shopping center in the world.",
		distance: "5 min walk",
		map: "",
	},
	{
		location: "International Market Place",
		tag: "shop",
		desc: "an open-air shopping center located in Waikīkī on the island of O‘ahu",
		distance: "15 min walk / 8 min drive",
		map: "",
	},
	{
		location: "Downtown Waikiki",
		tag: "shop",
		desc: " a vibrant neighborhood known for its popular surf beach. Designer fashion stores line Kalakaua Avenue and nearby streets, and the area buzzes after dark with waterside cocktail bars, fine dining and Kuhio Beach hula shows.",
		distance: "10 min walk",
		map: "",
	},
];

export default function Home() {
	return (
		<div className="text-slate-800">
			<Head>
				<title>Ala Wai</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="w-full px-20 min-h-screen lg:px-48">
				<div className="pt-8 font-sans flex justify-end space-x-8">
					<a className="underline underline-offset-2 hover:no-underline cursor-pointer">
						English
					</a>
					<a className="underline underline-offset-2 hover:no-underline cursor-pointer">
						한국어
					</a>
				</div>
				<div className="flex justify-center py-80  ">
					<div>
						<div className="font-serif font-semibold text-3xl sm:text-6xl">
							1551 Ala Wai Blvd
						</div>
						<div className="flex font-sans font-thin justify-around pt-8">
							<a
								href="#book"
								className="underline underline-offset-2 hover:no-underline"
							>
								Book
							</a>
							<a
								href="#book"
								className="underline underline-offset-2 hover:no-underline"
							>
								Contact
							</a>
						</div>
					</div>
				</div>
			</div>

			<div className="pb-12 px-20 lg:px-48">
				<div className="text-5xl py-8 space-y-3">
					<div className="font-serif font-semibold">
						Something about the property
					</div>
					<div className="text-xl text-justify font-thin font-sans">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
						eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
						ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
						aliquip ex ea commodo consequat. Duis aute irure dolor in
						reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
						pariatur.
					</div>
				</div>

				<div className="space-y-12">
					<PropertyCard />

					<div className="no-flex lg:flex lg:justify-center">
						<ApartmentCard />
					</div>
					<AMap />
				</div>
			</div>

			<div
				id="book"
				className="py-20 pb-40 px-20 lg:px-48 grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-0"
			>
				<Book />
				<Contact />
			</div>

			<div className="bg-slate-900 px-20 lg:px-48 py-12 text-white">
				<div className="text-xl font-thin">
					<div className="font-serif text-5xl">1551 Ala Wai Blvd</div>
					<div className="">Honolulu, HI</div>
					<div className="py-4">
						<a className="font-thin cursor-pointer underline underline-offset-2 hover:no-underline">
							julia@reality.com
						</a>
					</div>
					<div className="flex justify-end space-x-4">
						<a className="underline underline-offset-2 hover:no-underline cursor-pointer">
							English
						</a>
						<a className="underline underline-offset-2 hover:no-underline cursor-pointer">
							한국어
						</a>
					</div>
				</div>
			</div>
			<a href="github.com/friendlymatthew" target="_blank" rel="noreferrer">
				<div className="cursor-pointer flex space-x-4 bg-slate-700 py-2 px-20 lg:px-48 items-center">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						className="h-6 w-6 text-white"
						fill="none"
						viewBox="0 0 24 24"
						stroke="currentColor"
						strokeWidth="2"
					>
						<path
							strokeLinecap="round"
							strokeLinejoin="round"
							d="M12 11c0 3.517-1.009 6.799-2.753 9.571m-3.44-2.04l.054-.09A13.916 13.916 0 008 11a4 4 0 118 0c0 1.017-.07 2.019-.203 3m-2.118 6.844A21.88 21.88 0 0015.171 17m3.839 1.132c.645-2.266.99-4.659.99-7.132A8 8 0 008 4.07M3 15.364c.64-1.319 1-2.8 1-4.364 0-1.457.39-2.823 1.07-4"
						/>
					</svg>

					<div className="text-white">github.com/friendlymatthew</div>
				</div>
			</a>
		</div>
	);
}
